image: cirrusci/flutter:stable


stages:
  - build
  - pages


build:
  only:
      - master
      - develop

  stage: build

  script:
    - flutter pub get
    - flutter clean
    - flutter build apk --release

  artifacts:
    paths:
    - build/app/outputs/flutter-apk/app-release.apk



pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
