image: cirrusci/flutter:stable


stages:
  - pages


before_script:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python3-sphinx
  - sudo apt-get install -y python3-pip
  - apt install make
  - pip install sphinx-rtd-theme
  - pip install --upgrade myst-parser






pages:
  stage: pages
  script:
  - cd docs
  - make html
 
  artifacts:
    paths:
    - _build/html

