image: cirrusci/flutter:stable


stages:
  - build
  - pages


build:
  only:
      - master
      - develop

  stage: build

  script:
    - flutter pub get
    - flutter clean
    - flutter build apk --release

  artifacts:
    paths:
    - build/app/outputs/flutter-apk/app-release.apk


pages:
  only:
      - master
      - documentation
  stage: pages
  script:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:deadsnakes/ppa
  - sudo apt-get update
  - sudo apt-get install -y python3-sphinx
  - sudo apt-get install -y python3-pip
  - apt install make
  - pip install sphinx-rtd-theme
  - pip install --upgrade myst-parser
  - cd docs
  - make html
  - cd -
  - mv docs/_build/html/ public/

  artifacts:
    paths:
    - public


